Models/ErrorViewModel.cs
using System;

namespace AplikacijaZaPrijavuIzgradnjeKuca.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Prijavitelj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AplikacijaZaPrijavuOstecenjaSisMosZup.Models
{
    public class Prijavitelj
    {
        public int Id { get; set; }
        public string ImeVlasnikaTvrtke { get; set; }
        public string PrezimeVlasnikaTvrtke { get; set; }
        public string ImeTvrtke { get; set; }
        public short BrojGodinaPoslovanja { get; set; }
        public double OIBTvrtke { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public int KontaktBroj { get; set; }
        public int BrojRadnika { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AplikacijaZaPrijavuIzgradnjeKuca.Models;

namespace AplikacijaZaPrijavuIzgradnjeKuca.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PrijaviteljController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AplikacijaZaPrijavuIzgradnjeKuca.Data;
using AplikacijaZaPrijavuOstecenjaSisMosZup.Models;

namespace AplikacijaZaPrijavuIzgradnjeKuca.Controllers
{
    public class PrijaviteljController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PrijaviteljController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Prijavitelj
        public async Task<IActionResult> Index()
        {
            return View(await _context.Prijavitelj.ToListAsync());
        }

        // GET: Prijavitelj/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prijavitelj = await _context.Prijavitelj
                .FirstOrDefaultAsync(m => m.Id == id);
            if (prijavitelj == null)
            {
                return NotFound();
            }

            return View(prijavitelj);
        }

        // GET: Prijavitelj/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Prijavitelj/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImeVlasnikaTvrtke,PrezimeVlasnikaTvrtke,ImeTvrtke,BrojGodinaPoslovanja,OIBTvrtke,Adresa,Email,KontaktBroj,BrojRadnika")] Prijavitelj prijavitelj)
        {
            if (ModelState.IsValid)
            {
                _context.Add(prijavitelj);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prijavitelj);
        }

        // GET: Prijavitelj/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prijavitelj = await _context.Prijavitelj.FindAsync(id);
            if (prijavitelj == null)
            {
                return NotFound();
            }
            return View(prijavitelj);
        }

        // POST: Prijavitelj/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImeVlasnikaTvrtke,PrezimeVlasnikaTvrtke,ImeTvrtke,BrojGodinaPoslovanja,OIBTvrtke,Adresa,Email,KontaktBroj,BrojRadnika")] Prijavitelj prijavitelj)
        {
            if (id != prijavitelj.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prijavitelj);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrijaviteljExists(prijavitelj.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prijavitelj);
        }

        // GET: Prijavitelj/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prijavitelj = await _context.Prijavitelj
                .FirstOrDefaultAsync(m => m.Id == id);
            if (prijavitelj == null)
            {
                return NotFound();
            }

            return View(prijavitelj);
        }

        // POST: Prijavitelj/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prijavitelj = await _context.Prijavitelj.FindAsync(id);
            _context.Prijavitelj.Remove(prijavitelj);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrijaviteljExists(int id)
        {
            return _context.Prijavitelj.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Dobrodošli na naš portal.</h1>
        <p>Molimo da odaberete jednu od sljedećih usluga: </p>
        <hr />
        <a asp-controller="Prijavitelj" asp-action="Create">Prijavi svoju građevinsku tvrtku za izgradnju kuća u Petrinji.</a>
        <hr />
        <a asp-controller="Prijavitelj" asp-action="Create">Prijavi svoju građevinsku tvrtku za izgradnju kuća u Glini.</a>
        <hr />
        <a asp-controller="Prijavitelj" asp-action="Create">Prijavi svoju građevinsku tvrtku za izgradnju kuća u Sisku.</a>
    </div>

Views/Prijavitelj/Create.cshtml
@model AplikacijaZaPrijavuOstecenjaSisMosZup.Models.Prijavitelj

@{
    ViewData["Title"] = "Create";
}


<hr />
<div class="row" style="border: 1px solid grey; padding: 20px; border-radius: 10px;">
    <div class="col-md-9" style="float:none;margin:auto; text-align: center;">
        <h1>Prijavi tvrtku</h1>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Ime vlasnika tvrtke
                <input asp-for="ImeVlasnikaTvrtke" class="form-control" />
                <span asp-validation-for="ImeVlasnikaTvrtke" class="text-danger"></span>
            </div>
            <div class="form-group">
                Prezime vlasnika tvrtke
                <input asp-for="PrezimeVlasnikaTvrtke" class="form-control" />
                <span asp-validation-for="PrezimeVlasnikaTvrtke" class="text-danger"></span>
            </div>
            <div class="form-group">
                Ime tvrtke
                <input asp-for="ImeTvrtke" class="form-control" />
                <span asp-validation-for="ImeTvrtke" class="text-danger"></span>
            </div>
            <div class="form-group">
                Broj godina poslovanja
                <input asp-for="BrojGodinaPoslovanja" class="form-control" />
                <span asp-validation-for="BrojGodinaPoslovanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                OIB tvrtke
                <input asp-for="OIBTvrtke" class="form-control" />
                <span asp-validation-for="OIBTvrtke" class="text-danger"></span>
            </div>
            <div class="form-group">
                Adresa
                <input asp-for="Adresa" class="form-control" />
                <span asp-validation-for="Adresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                Kontakt e-mail
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                Kontakt broj
                <input asp-for="KontaktBroj" class="form-control" />
                <span asp-validation-for="KontaktBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                Broj radnika
                <input asp-for="BrojRadnika" class="form-control" />
                <span asp-validation-for="BrojRadnika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Prijavitelj/Delete.cshtml
@model AplikacijaZaPrijavuOstecenjaSisMosZup.Models.Prijavitelj

@{
    ViewData["Title"] = "Delete";
}

<h1>Obriši tvrtku</h1>

<div>
    <h4>Prijavitelj</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Ime vlasnika tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImeVlasnikaTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Prezime vlasnika tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrezimeVlasnikaTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Ime tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImeTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Godine poslovanja
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrojGodinaPoslovanja)
        </dd>
        <dt class = "col-sm-2">
            OIB tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OIBTvrtke)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            Kontakt broj
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KontaktBroj)
        </dd>
        <dt class = "col-sm-2">
            Broj radnika
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrojRadnika)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Views/Prijavitelj/Details.cshtml
@model AplikacijaZaPrijavuOstecenjaSisMosZup.Models.Prijavitelj

@{
    ViewData["Title"] = "Details";
}

<h1>Detalji tvrtke</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Ime vlasnika tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImeVlasnikaTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Prezime vlasnika tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrezimeVlasnikaTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Ime tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImeTvrtke)
        </dd>
        <dt class = "col-sm-2">
            Godine poslovanja
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrojGodinaPoslovanja)
        </dd>
        <dt class = "col-sm-2">
            OIB tvrtke
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OIBTvrtke)
        </dd>
        <dt class = "col-sm-2">
           Adresa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt class = "col-sm-2">
            Email
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            Kontakt broj
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KontaktBroj)
        </dd>
        <dt class = "col-sm-2">
            Broj radnika
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrojRadnika)
        </dd>
    </dl>
</div>

Views/Prijavitelj/Index.cshtml
@model IEnumerable<AplikacijaZaPrijavuOstecenjaSisMosZup.Models.Prijavitelj>

@{
    ViewData["Title"] = "Index";
}

<h1>Pogledaj sve prijavitelje</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Ime vlasnika tvrtke
            </th>
            <th>
                Prezime vlasnika tvrtke
            </th>
            <th>
                Ime tvrtke
            </th>
            <th>
                Broj godina poslovanja
            </th>
            <th>
                OIB tvrtke
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Kontakt broj
            </th>
            <th>
                Broj radnika
            </th>s
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ImeVlasnikaTvrtke)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrezimeVlasnikaTvrtke)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImeTvrtke)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojGodinaPoslovanja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OIBTvrtke)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KontaktBroj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojRadnika)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Detalji</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aplikacija Za Prijavu Izgradnje Kuca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplikacijaZaPrijavuIzgradnjeKuca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prijavitelj" asp-action="Create">Prijavi svoju građevinsku tvrtku za pomoć</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NetMedia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>